# Generated by Django 4.2.23 on 2025-07-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40)),
                ('client_age', models.IntegerField(default=50)),
                ('loction', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=40)),
                ('contact_number', models.IntegerField(default=40)),
                ('fees', models.BooleanField(default=True)),
            ],
        ),
    ]
