# Generated by Django 4.2.23 on 2025-07-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='client_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='contact_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
